language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - git clone --branch=devel https://github.com/tasoc/photometry.git ../photometry
script:
  - make html
branches:
  only:
    - master
    - devel
